services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=students'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'

  pdadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: almouslecka@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'